[package]
name = "staking_fuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-test = { path = "../../../../anchor-test" }
anchor-test-context = { path = "../../../../anchor-test/anchor-test-context" }
anchor-lang = { path = "../../../../../lang" }
arbitrary = { version = "1", features = ["derive"] }
libafl = { version = "0.15.1", features = ["std", "cli", "prelude"] }
libafl_bolts = { version = "0.15.1", features = ["std"] }
solana-keypair = "3.0"
solana-pubkey = "3.0"
solana-signer = "3.0"

staking = { path = "../../programs/staking", features = ["no-entrypoint"] }

[features]
fuzz_staking = []
invariant_fuzz = []
fuzz_single_stake = []
invariant_fuzz_batched = []
