[package]
name = "anchor_counter"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "anchor_counter"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
#idl-build = ["anchor-lang/idl-build"]
test-sbf = []

[dependencies]
anchor-lang = "0.31.1"

[dev-dependencies]
anchor_counter = { path = ".", features = ["no-entrypoint"] }
spl-token = { version = "6.0", features = ["no-entrypoint"] }
anchor-test = { path = "../../../../anchor-test" }
anchor-test-context = { path = "../../../../anchor-test/anchor-test-context" }
solana-sdk = "=2.2.1"
solana-program = "=2.2.1"

