[package]
name = "anchor-test-context"
version = "0.1.0"
edition = "2021"

[dependencies]
litesvm.workspace = true
anchor-lang.workspace = true

spl-token.workspace = true
solana-sdk.workspace = true
solana-program.workspace = true
solana-program-pack.workspace = true
solana-message.workspace = true
anyhow.workspace = true
