[package]
name = "anchor-test"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "anchor-test-context", 
    "anchor-fuzz-macro",
    "anchor-invariant-macro",
]
resolver = "2"


[workspace.dependencies]
anyhow = "1.0"
litesvm = { git = "https://github.com/asymmetric-research/litesvm-tracing", branch = "v0.7.1-with-tracing" }
anchor-lang = "0.32.1"
solana-program = "2.3"
solana-sdk = "2.3"
solana-message = "2.3"
solana-program-pack = "2.2"
spl-token = "7.0.0"

[dependencies]
rand = "0.8"
anyhow = { workspace = true }
anchor-test-context = { path = "./anchor-test-context" }
anchor-fuzz-macro = { path = "./anchor-fuzz-macro" }
anchor-invariant-macro = { path = "./anchor-invariant-macro" }

[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.unused_import_braces = "allow"
clippy.wildcard_imports = "deny"

[features]
no-entrypoint = []

