[package]
name = "crucible-fuzz-macro"
version = "0.2.1"
edition = "2021"
rust-version.workspace = true
license.workspace = true
description = "Fuzzing macros for crucible-fuzzer"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
crucible-macro-utils = { path = "../crucible-macro-utils", version = "0.2.1" }
