use crate::action::FuzzAction;
use crate::mutators::primitives::{
    gen_range_u64, gen_range_usize, mutate_bool, mutate_i64, mutate_u64, mutate_usize, rand_below,
};
use libafl_bolts::rands::Rand;

/// Test action enum mirroring a realistic fuzz harness with 6 variant types.
/// Manually implements FuzzAction following the exact patterns generated by `#[fuzz_fixture]`.
#[derive(Clone, Debug, PartialEq)]
pub enum TestAction {
    NoFields,
    OneField {
        amount: u64,
    },
    TwoFields {
        user_idx: usize,
        flag: bool,
    },
    FourFields {
        a: u64,
        b: usize,
        c: u64,
        d: bool,
    },
    SixFields {
        a: u64,
        b: u64,
        c: usize,
        d: usize,
        e: u64,
        f: bool,
    },
    /// Vec<u64> field with max_len=4, range 0..1000 on elements
    /// Byte size: (1 + 4) * 8 = 40
    VecField {
        items: Vec<u64>,
    },
}

const VEC_MAX_LEN: usize = 4;
const VEC_BYTE_SIZE: usize = (1 + VEC_MAX_LEN) * 8; // 40
const VEC_LO: u64 = 0;
const VEC_HI: u64 = 1000;

impl FuzzAction for TestAction {
    fn variant_count() -> usize {
        6
    }

    fn random_variant<R: Rand>(variant_idx: usize, rng: &mut R) -> Self {
        match variant_idx % 6 {
            0 => Self::NoFields,
            1 => Self::OneField {
                amount: gen_range_u64(rng, 1, 100_000_000),
            },
            2 => Self::TwoFields {
                user_idx: gen_range_usize(rng, 0, 3),
                flag: rand_below(rng, 2) == 1,
            },
            3 => Self::FourFields {
                a: gen_range_u64(rng, 0, 1_000_000),
                b: gen_range_usize(rng, 0, 10),
                c: rng.next(),
                d: rand_below(rng, 2) == 1,
            },
            4 => Self::SixFields {
                a: gen_range_u64(rng, 1, 100_000_000),
                b: rng.next(),
                c: gen_range_usize(rng, 0, 5),
                d: gen_range_usize(rng, 0, 3),
                e: gen_range_u64(rng, 0, 1_000_000),
                f: rand_below(rng, 2) == 1,
            },
            5 => {
                let len = rand_below(rng, VEC_MAX_LEN + 1);
                let items: Vec<u64> = (0..len)
                    .map(|_| gen_range_u64(rng, VEC_LO, VEC_HI))
                    .collect();
                Self::VecField { items }
            }
            _ => unreachable!(),
        }
    }

    fn mutate<R: Rand>(&mut self, rng: &mut R) {
        match self {
            Self::NoFields => {}
            Self::OneField { amount } => {
                let num_mutations = 1 + rand_below(rng, 1usize.min(3));
                for _ in 0..num_mutations {
                    match rand_below(rng, 1) {
                        0 => mutate_u64(amount, 1, 100_000_000, rng),
                        _ => {}
                    }
                }
            }
            Self::TwoFields { user_idx, flag } => {
                let num_mutations = 1 + rand_below(rng, 2usize.min(3));
                for _ in 0..num_mutations {
                    match rand_below(rng, 2) {
                        0 => mutate_usize(user_idx, 0, 3, rng),
                        1 => mutate_bool(flag, rng),
                        _ => {}
                    }
                }
            }
            Self::FourFields { a, b, c, d } => {
                let num_mutations = 1 + rand_below(rng, 4usize.min(3));
                for _ in 0..num_mutations {
                    match rand_below(rng, 4) {
                        0 => mutate_u64(a, 0, 1_000_000, rng),
                        1 => mutate_usize(b, 0, 10, rng),
                        2 => mutate_u64(c, 0, u64::MAX, rng),
                        3 => mutate_bool(d, rng),
                        _ => {}
                    }
                }
            }
            Self::SixFields { a, b, c, d, e, f } => {
                let num_mutations = 1 + rand_below(rng, 6usize.min(3));
                for _ in 0..num_mutations {
                    match rand_below(rng, 6) {
                        0 => mutate_u64(a, 1, 100_000_000, rng),
                        1 => mutate_u64(b, 0, u64::MAX, rng),
                        2 => mutate_usize(c, 0, 5, rng),
                        3 => mutate_usize(d, 0, 3, rng),
                        4 => mutate_u64(e, 0, 1_000_000, rng),
                        5 => mutate_bool(f, rng),
                        _ => {}
                    }
                }
            }
            Self::VecField { items } => {
                // 20% change length, 80% mutate random element
                if rand_below(rng, 100) < 20 {
                    if items.is_empty() || rand_below(rng, 2) == 0 {
                        if items.len() < VEC_MAX_LEN {
                            items.push(gen_range_u64(rng, VEC_LO, VEC_HI));
                        }
                    } else {
                        let idx = rand_below(rng, items.len());
                        items.remove(idx);
                    }
                } else if !items.is_empty() {
                    let idx = rand_below(rng, items.len());
                    mutate_u64(&mut items[idx], VEC_LO, VEC_HI, rng);
                }
            }
        }
    }

    fn action_name(&self) -> &'static str {
        match self {
            Self::NoFields => "no_fields",
            Self::OneField { .. } => "one_field",
            Self::TwoFields { .. } => "two_fields",
            Self::FourFields { .. } => "four_fields",
            Self::SixFields { .. } => "six_fields",
            Self::VecField { .. } => "vec_field",
        }
    }

    fn variant_index(&self) -> usize {
        match self {
            Self::NoFields => 0,
            Self::OneField { .. } => 1,
            Self::TwoFields { .. } => 2,
            Self::FourFields { .. } => 3,
            Self::SixFields { .. } => 4,
            Self::VecField { .. } => 5,
        }
    }

    fn serialize_fields(&self, buf: &mut Vec<u8>) {
        match self {
            Self::NoFields => {}
            Self::OneField { amount } => {
                buf.extend_from_slice(&amount.to_le_bytes());
            }
            Self::TwoFields { user_idx, flag } => {
                buf.extend_from_slice(&(*user_idx as u64).to_le_bytes());
                buf.extend_from_slice(&(if *flag { 1u64 } else { 0u64 }).to_le_bytes());
            }
            Self::FourFields { a, b, c, d } => {
                buf.extend_from_slice(&a.to_le_bytes());
                buf.extend_from_slice(&(*b as u64).to_le_bytes());
                buf.extend_from_slice(&c.to_le_bytes());
                buf.extend_from_slice(&(if *d { 1u64 } else { 0u64 }).to_le_bytes());
            }
            Self::SixFields { a, b, c, d, e, f } => {
                buf.extend_from_slice(&a.to_le_bytes());
                buf.extend_from_slice(&b.to_le_bytes());
                buf.extend_from_slice(&(*c as u64).to_le_bytes());
                buf.extend_from_slice(&(*d as u64).to_le_bytes());
                buf.extend_from_slice(&e.to_le_bytes());
                buf.extend_from_slice(&(if *f { 1u64 } else { 0u64 }).to_le_bytes());
            }
            Self::VecField { items } => {
                buf.extend_from_slice(&(items.len() as u64).to_le_bytes());
                for item in items {
                    buf.extend_from_slice(&item.to_le_bytes());
                }
                for _ in items.len()..VEC_MAX_LEN {
                    buf.extend_from_slice(&0u64.to_le_bytes());
                }
            }
        }
    }

    fn deserialize_fields(variant_idx: usize, bytes: &[u8], cursor: &mut usize) -> Option<Self> {
        match variant_idx {
            0 => Some(Self::NoFields),
            1 => {
                if *cursor + 8 > bytes.len() {
                    return None;
                }
                let amount = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                *cursor += 8;
                Some(Self::OneField { amount })
            }
            2 => {
                if *cursor + 16 > bytes.len() {
                    return None;
                }
                let user_idx =
                    u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as usize;
                *cursor += 8;
                let flag = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) != 0;
                *cursor += 8;
                Some(Self::TwoFields { user_idx, flag })
            }
            3 => {
                if *cursor + 32 > bytes.len() {
                    return None;
                }
                let a = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                *cursor += 8;
                let b = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as usize;
                *cursor += 8;
                let c = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                *cursor += 8;
                let d = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) != 0;
                *cursor += 8;
                Some(Self::FourFields { a, b, c, d })
            }
            4 => {
                if *cursor + 48 > bytes.len() {
                    return None;
                }
                let a = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                *cursor += 8;
                let b = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                *cursor += 8;
                let c = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as usize;
                *cursor += 8;
                let d = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as usize;
                *cursor += 8;
                let e = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                *cursor += 8;
                let f = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) != 0;
                *cursor += 8;
                Some(Self::SixFields { a, b, c, d, e, f })
            }
            5 => {
                if *cursor + VEC_BYTE_SIZE > bytes.len() {
                    return None;
                }
                let len = (u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?)
                    as usize)
                    .min(VEC_MAX_LEN);
                *cursor += 8;
                let mut items = Vec::with_capacity(len);
                for i in 0..VEC_MAX_LEN {
                    let v = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                    if i < len {
                        items.push(v);
                    }
                    *cursor += 8;
                }
                Some(Self::VecField { items })
            }
            _ => None,
        }
    }

    fn field_byte_count(variant_idx: usize) -> usize {
        match variant_idx {
            0 => 0,             // NoFields
            1 => 8,             // OneField: 1 * 8
            2 => 16,            // TwoFields: 2 * 8
            3 => 32,            // FourFields: 4 * 8
            4 => 48,            // SixFields: 6 * 8
            5 => VEC_BYTE_SIZE, // VecField: (1+4)*8 = 40
            _ => 0,
        }
    }

    fn from_name_and_params(name: &str, params: &serde_json::Value) -> Option<Self> {
        match name {
            "no_fields" => Some(Self::NoFields),
            "one_field" => Some(Self::OneField {
                amount: params.get("amount")?.as_u64()?,
            }),
            "two_fields" => Some(Self::TwoFields {
                user_idx: params.get("user_idx")?.as_u64()? as usize,
                flag: params.get("flag")?.as_bool()?,
            }),
            "four_fields" => Some(Self::FourFields {
                a: params.get("a")?.as_u64()?,
                b: params.get("b")?.as_u64()? as usize,
                c: params.get("c")?.as_u64()?,
                d: params.get("d")?.as_bool()?,
            }),
            "six_fields" => Some(Self::SixFields {
                a: params.get("a")?.as_u64()?,
                b: params.get("b")?.as_u64()?,
                c: params.get("c")?.as_u64()? as usize,
                d: params.get("d")?.as_u64()? as usize,
                e: params.get("e")?.as_u64()?,
                f: params.get("f")?.as_bool()?,
            }),
            "vec_field" => {
                let arr = params.get("items")?.as_array()?;
                let items: Option<Vec<u64>> = arr.iter().map(|v| v.as_u64()).collect();
                Some(Self::VecField { items: items? })
            }
            _ => None,
        }
    }
}

// ============================================================================
// SmallIntTestAction — exercises u8/u16/u32/i8/i16/i32 serialization paths
// ============================================================================
//
// This mirrors the code the *fixed* macro generates for sub-64-bit integer types.
// The key patterns being tested:
// - Serialize: cast to u64 first, then .to_le_bytes() (Fix 1a/1c)
// - Deserialize: u64::from_le_bytes(...) then cast down to target type (Fix 1b/1d/1e)

const SMALL_VEC_MAX_LEN: usize = 3;
const SMALL_VEC_BYTE_SIZE: usize = (1 + SMALL_VEC_MAX_LEN) * 8; // 32

#[derive(Clone, Debug, PartialEq)]
pub enum SmallIntTestAction {
    /// u8 + u16 + u32 scalar fields (Fix 1a serialization, Fix 1b deserialization)
    UnsignedSmall { a: u8, b: u16, c: u32 },
    /// i8 + i16 + i32 signed scalar fields
    SignedSmall { x: i8, y: i16, z: i32 },
    /// Vec<u16> — tests Fix 1c (vec element ser) and Fix 1d (vec element deser)
    VecU16 { items: Vec<u16> },
    /// Option<u8> — tests Fix 1e (option inner deser)
    OptionU8 { val: Option<u8> },
    /// Mixed: u8 + i16 + Option<u32> in one variant
    Mixed {
        small: u8,
        signed: i16,
        opt: Option<u32>,
    },
}

impl FuzzAction for SmallIntTestAction {
    fn variant_count() -> usize {
        5
    }

    fn random_variant<R: Rand>(variant_idx: usize, rng: &mut R) -> Self {
        match variant_idx % 5 {
            0 => Self::UnsignedSmall {
                a: gen_range_u64(rng, 0, 256) as u8,
                b: gen_range_u64(rng, 0, 65536) as u16,
                c: gen_range_u64(rng, 0, u32::MAX as u64 + 1) as u32,
            },
            1 => Self::SignedSmall {
                x: rng.next() as i8,
                y: rng.next() as i16,
                z: rng.next() as i32,
            },
            2 => {
                let len = rand_below(rng, SMALL_VEC_MAX_LEN + 1);
                let items: Vec<u16> = (0..len)
                    .map(|_| gen_range_u64(rng, 0, 65536) as u16)
                    .collect();
                Self::VecU16 { items }
            }
            3 => Self::OptionU8 {
                val: if rand_below(rng, 4) == 0 {
                    None
                } else {
                    Some(gen_range_u64(rng, 0, 256) as u8)
                },
            },
            4 => Self::Mixed {
                small: gen_range_u64(rng, 0, 256) as u8,
                signed: rng.next() as i16,
                opt: if rand_below(rng, 4) == 0 {
                    None
                } else {
                    Some(rng.next() as u32)
                },
            },
            _ => unreachable!(),
        }
    }

    fn mutate<R: Rand>(&mut self, rng: &mut R) {
        match self {
            Self::UnsignedSmall { a, b, c } => match rand_below(rng, 3) {
                0 => {
                    let mut v = *a as u64;
                    mutate_u64(&mut v, 0, 256, rng);
                    *a = v as u8;
                }
                1 => {
                    let mut v = *b as u64;
                    mutate_u64(&mut v, 0, 65536, rng);
                    *b = v as u16;
                }
                2 => {
                    let mut v = *c as u64;
                    mutate_u64(&mut v, 0, u32::MAX as u64 + 1, rng);
                    *c = v as u32;
                }
                _ => {}
            },
            Self::SignedSmall { x, y, z } => match rand_below(rng, 3) {
                0 => {
                    let mut v = *x as i64;
                    mutate_i64(&mut v, i8::MIN as i64, i8::MAX as i64 + 1, rng);
                    *x = v as i8;
                }
                1 => {
                    let mut v = *y as i64;
                    mutate_i64(&mut v, i16::MIN as i64, i16::MAX as i64 + 1, rng);
                    *y = v as i16;
                }
                2 => {
                    let mut v = *z as i64;
                    mutate_i64(&mut v, i32::MIN as i64, i32::MAX as i64 + 1, rng);
                    *z = v as i32;
                }
                _ => {}
            },
            Self::VecU16 { items } => {
                if rand_below(rng, 100) < 20 {
                    if items.is_empty() || rand_below(rng, 2) == 0 {
                        if items.len() < SMALL_VEC_MAX_LEN {
                            items.push(gen_range_u64(rng, 0, 65536) as u16);
                        }
                    } else {
                        let idx = rand_below(rng, items.len());
                        items.remove(idx);
                    }
                } else if !items.is_empty() {
                    let idx = rand_below(rng, items.len());
                    let mut v = items[idx] as u64;
                    mutate_u64(&mut v, 0, 65536, rng);
                    items[idx] = v as u16;
                }
            }
            Self::OptionU8 { val } => {
                if rand_below(rng, 100) < 15 {
                    *val = if val.is_some() {
                        None
                    } else {
                        Some(gen_range_u64(rng, 0, 256) as u8)
                    };
                } else if let Some(ref mut inner) = val {
                    let mut v = *inner as u64;
                    mutate_u64(&mut v, 0, 256, rng);
                    *inner = v as u8;
                }
            }
            Self::Mixed { small, signed, opt } => match rand_below(rng, 3) {
                0 => {
                    let mut v = *small as u64;
                    mutate_u64(&mut v, 0, 256, rng);
                    *small = v as u8;
                }
                1 => {
                    let mut v = *signed as i64;
                    mutate_i64(&mut v, i16::MIN as i64, i16::MAX as i64 + 1, rng);
                    *signed = v as i16;
                }
                2 => {
                    if rand_below(rng, 100) < 15 {
                        *opt = if opt.is_some() {
                            None
                        } else {
                            Some(rng.next() as u32)
                        };
                    } else if let Some(ref mut inner) = opt {
                        let mut v = *inner as u64;
                        mutate_u64(&mut v, 0, u64::MAX, rng);
                        *inner = v as u32;
                    }
                }
                _ => {}
            },
        }
    }

    fn action_name(&self) -> &'static str {
        match self {
            Self::UnsignedSmall { .. } => "unsigned_small",
            Self::SignedSmall { .. } => "signed_small",
            Self::VecU16 { .. } => "vec_u16",
            Self::OptionU8 { .. } => "option_u8",
            Self::Mixed { .. } => "mixed",
        }
    }

    fn variant_index(&self) -> usize {
        match self {
            Self::UnsignedSmall { .. } => 0,
            Self::SignedSmall { .. } => 1,
            Self::VecU16 { .. } => 2,
            Self::OptionU8 { .. } => 3,
            Self::Mixed { .. } => 4,
        }
    }

    fn serialize_fields(&self, buf: &mut Vec<u8>) {
        match self {
            // Fix 1a: cast to u64 before .to_le_bytes() — the bug was calling
            // .to_le_bytes() directly on u8 (1 byte) / u16 (2 bytes) / u32 (4 bytes)
            Self::UnsignedSmall { a, b, c } => {
                buf.extend_from_slice(&(*a as u64).to_le_bytes());
                buf.extend_from_slice(&(*b as u64).to_le_bytes());
                buf.extend_from_slice(&(*c as u64).to_le_bytes());
            }
            Self::SignedSmall { x, y, z } => {
                buf.extend_from_slice(&(*x as u64).to_le_bytes());
                buf.extend_from_slice(&(*y as u64).to_le_bytes());
                buf.extend_from_slice(&(*z as u64).to_le_bytes());
            }
            // Fix 1c: vec element serialization casts through u64
            Self::VecU16 { items } => {
                buf.extend_from_slice(&(items.len() as u64).to_le_bytes());
                for item in items {
                    buf.extend_from_slice(&(*item as u64).to_le_bytes());
                }
                for _ in items.len()..SMALL_VEC_MAX_LEN {
                    buf.extend_from_slice(&0u64.to_le_bytes());
                }
            }
            Self::OptionU8 { val } => match val {
                Some(v) => buf.extend_from_slice(&(*v as u64).to_le_bytes()),
                None => buf.extend_from_slice(&u64::MAX.to_le_bytes()),
            },
            Self::Mixed { small, signed, opt } => {
                buf.extend_from_slice(&(*small as u64).to_le_bytes());
                buf.extend_from_slice(&(*signed as u64).to_le_bytes());
                match opt {
                    Some(v) => buf.extend_from_slice(&(*v as u64).to_le_bytes()),
                    None => buf.extend_from_slice(&u64::MAX.to_le_bytes()),
                }
            }
        }
    }

    fn deserialize_fields(variant_idx: usize, bytes: &[u8], cursor: &mut usize) -> Option<Self> {
        match variant_idx {
            0 => {
                // Fix 1b: cast u64 down to target type
                if *cursor + 24 > bytes.len() {
                    return None;
                }
                let a = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as u8;
                *cursor += 8;
                let b = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as u16;
                *cursor += 8;
                let c = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as u32;
                *cursor += 8;
                Some(Self::UnsignedSmall { a, b, c })
            }
            1 => {
                if *cursor + 24 > bytes.len() {
                    return None;
                }
                let x = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as i8;
                *cursor += 8;
                let y = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as i16;
                *cursor += 8;
                let z = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as i32;
                *cursor += 8;
                Some(Self::SignedSmall { x, y, z })
            }
            2 => {
                // Fix 1d: vec element deserialization casts through u64
                if *cursor + SMALL_VEC_BYTE_SIZE > bytes.len() {
                    return None;
                }
                let len = (u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?)
                    as usize)
                    .min(SMALL_VEC_MAX_LEN);
                *cursor += 8;
                let mut items = Vec::with_capacity(len);
                for i in 0..SMALL_VEC_MAX_LEN {
                    let raw = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                    if i < len {
                        items.push(raw as u16);
                    }
                    *cursor += 8;
                }
                Some(Self::VecU16 { items })
            }
            3 => {
                // Fix 1e: option inner deserialization casts through u64
                if *cursor + 8 > bytes.len() {
                    return None;
                }
                let raw = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                let val = if raw == u64::MAX {
                    None
                } else {
                    Some(raw as u8)
                };
                *cursor += 8;
                Some(Self::OptionU8 { val })
            }
            4 => {
                if *cursor + 24 > bytes.len() {
                    return None;
                }
                let small = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as u8;
                *cursor += 8;
                let signed =
                    u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?) as i16;
                *cursor += 8;
                let raw = u64::from_le_bytes(bytes[*cursor..*cursor + 8].try_into().ok()?);
                let opt = if raw == u64::MAX {
                    None
                } else {
                    Some(raw as u32)
                };
                *cursor += 8;
                Some(Self::Mixed { small, signed, opt })
            }
            _ => None,
        }
    }

    fn field_byte_count(variant_idx: usize) -> usize {
        match variant_idx {
            0 => 24,                  // UnsignedSmall: 3 * 8
            1 => 24,                  // SignedSmall: 3 * 8
            2 => SMALL_VEC_BYTE_SIZE, // VecU16: (1+3)*8 = 32
            3 => 8,                   // OptionU8: 1 * 8
            4 => 24,                  // Mixed: 3 * 8
            _ => 0,
        }
    }

    fn from_name_and_params(name: &str, params: &serde_json::Value) -> Option<Self> {
        match name {
            "unsigned_small" => Some(Self::UnsignedSmall {
                a: params.get("a")?.as_u64()? as u8,
                b: params.get("b")?.as_u64()? as u16,
                c: params.get("c")?.as_u64()? as u32,
            }),
            "signed_small" => Some(Self::SignedSmall {
                x: params.get("x")?.as_i64()? as i8,
                y: params.get("y")?.as_i64()? as i16,
                z: params.get("z")?.as_i64()? as i32,
            }),
            "vec_u16" => {
                let arr = params.get("items")?.as_array()?;
                let items: Option<Vec<u16>> =
                    arr.iter().map(|v| v.as_u64().map(|n| n as u16)).collect();
                Some(Self::VecU16 { items: items? })
            }
            "option_u8" => {
                let val = match params.get("val") {
                    Some(v) if v.is_null() => None,
                    Some(v) => Some(v.as_u64()? as u8),
                    None => None,
                };
                Some(Self::OptionU8 { val })
            }
            "mixed" => {
                let opt = match params.get("opt") {
                    Some(v) if v.is_null() => None,
                    Some(v) => Some(v.as_u64()? as u32),
                    None => None,
                };
                Some(Self::Mixed {
                    small: params.get("small")?.as_u64()? as u8,
                    signed: params.get("signed")?.as_i64()? as i16,
                    opt,
                })
            }
            _ => None,
        }
    }
}
