[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
owner_mutation_airdrop = "2eJW8mrzmW3Gy88VZ5oqn4qSRoTRYqQfucG69mx99F1b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "true"
