[package]
name = "crucible-fuzzer"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Solana smart contract fuzzing framework"

[dependencies]
rand = "0.8"
anyhow = { workspace = true }
crucible-test-context = { path = "../crucible-test-context", version = "0.2.1" }
crucible-fuzz-macro = { path = "../crucible-fuzz-macro", version = "0.2.1" }
crucible-invariant-macro = { path = "../crucible-invariant-macro", version = "0.2.1" }
crucible-fuzz-runtime = { path = "../crucible-fuzz-runtime", version = "0.2.1" }
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
mimalloc = { version = "0.1", default-features = false }
libc = "0.2"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.10"

[features]
no-entrypoint = []
