use std::sync::atomic::{AtomicU32, Ordering};

macro_rules! define_counters {
    ($($name:ident),*) => {
        $(pub static $name: (AtomicU32, AtomicU32) = (AtomicU32::new(0), AtomicU32::new(0));)*
    }
}

define_counters!(
    SWAP, INCREASE_LIQUIDITY, DECREASE_LIQUIDITY,
    UPDATE_FEES, COLLECT_FEES, OPEN_POSITION, CLOSE_POSITION,
    INITIALIZE_REWARD, SET_REWARD_EMISSIONS, COLLECT_REWARD,
    COLLECT_PROTOCOL_FEES, SET_FEE_RATE, SET_PROTOCOL_FEE_RATE,
    EXACT_OUT_SWAP, ADVANCE_TIME,
    RESET_POSITION_RANGE, INIT_TICK_ARRAY,
    SET_DEFAULT_FEE_RATE, SET_DEFAULT_PROTOCOL_FEE_RATE,
    TWO_HOP_SWAP, SET_FEE_AUTHORITY, SET_REWARD_AUTHORITY,
    SET_COLLECT_PROTO_FEES_AUTHORITY,
    INIT_POSITION_BUNDLE, OPEN_BUNDLED_POSITION,
    CLOSE_BUNDLED_POSITION, DELETE_POSITION_BUNDLE,
    SET_REWARD_EMISSIONS_SUPER_AUTH,
    DRAIN_AND_CLOSE, SWAP_POOL_TWO, OPEN_EXTREME_POSITION,
    ROUNDTRIP_LIQUIDITY,
    EXACT_OUT_SWAP_POOL_TWO, OPEN_DUPLICATE_RANGE,
    SWAP_V2, TWO_HOP_SWAP_V2, COLLECT_FEES_V2, COLLECT_PROTOCOL_FEES_V2,
    COLLECT_REWARD_V2, INCREASE_LIQUIDITY_V2, DECREASE_LIQUIDITY_V2,
    SET_REWARD_EMISSIONS_V2, SET_REWARD_AUTH_BY_SUPER,
    INIT_CONFIG_EXTENSION, SET_CONFIG_EXT_AUTH, SET_TOKEN_BADGE_AUTH,
    ZERO_FEE_SWAP, EXTREME_REWARD_EMISSIONS, WRONG_AUTHORITY_FEE,
    SET_CONFIG_FEATURE_FLAG, INIT_TOKEN_BADGE, DELETE_TOKEN_BADGE,
    SET_TOKEN_BADGE_ATTR, OPEN_POSITION_P2, INCREASE_LIQ_P2,
    DECREASE_LIQ_P2, SWAP_EXACT_OUT_V2, SEQUENTIAL_MICRO_SWAPS,
    FULL_CYCLE, CROSS_TICK_SWAP, MIGRATE_REWARD_AUTH,
    INIT_DYNAMIC_TICK_ARRAY, SWAP_P3, SET_DEFAULT_BASE_FEE,
    SET_DELEGATED_FEE_AUTH, FEE_RATE_BY_DELEGATED, SET_PRESET_ADAPTIVE_FEE,
    OPEN_POSITION_P3, INCREASE_LIQ_P3, DECREASE_LIQ_P3,
    SET_INIT_POOL_AUTH, SWAP_V2_P3,
    HIGH_LIQ_FEE_COLLECT, VOLATILITY_INFLATION,
    OPEN_POS_TOKEN_EXT, CLOSE_POS_TOKEN_EXT,
    LOCK_POSITION, TRANSFER_LOCKED_POSITION,
    INIT_REWARD_V2, DRAIN_SWAP
);

pub fn record(counter: &(AtomicU32, AtomicU32), success: bool) {
    if success {
        counter.0.fetch_add(1, Ordering::Relaxed);
    } else {
        counter.1.fetch_add(1, Ordering::Relaxed);
    }
}

pub fn print_summary() {
    // no-op: debug prints removed for performance
}
